rabbitmq:
  host: 'localhost'
  port: 5672
  username: 'guest'
  password: 'guest'
  vhost: '/'

queue:
  name: 'order_processing'
  durable: true
  exchange: 'orders'
  routing_key: 'order.new'

producer_settings:
  delivery_mode: 2
  content_type: 'application/json'
  publish_rate_limit: 1000

logging:
  level: 'INFO'
  file: '/var/log/producer.log'