resources:
  - resource_name: hapmap_3.3_grch38_sites
    reference_build: GRCh38
    chromosome_naming: chr
    variant_count: 1457897
    chromosomes_covered: 23
    file_path: /data/resources/hapmap_3.3.hg38.vcf.gz
  - resource_name: omni_2.5_grch38_sites
    reference_build: GRCh38
    chromosome_naming: numeric
    variant_count: 1211267
    chromosomes_covered: 22
    file_path: /data/resources/1000G_omni2.5.hg38.vcf.gz
  - resource_name: mills_indels_grch38
    reference_build: GRCh38
    chromosome_naming: chr
    variant_count: 2134567
    chromosomes_covered: 24
    file_path: /data/resources/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz