training_datasets:
  - resource_name: hapmap_3.3
    reference_build: GRCh38
    chromosome_naming: chr
    variant_count: 1457897
    chromosomes_covered: 23
    file_path: /data/resources/hapmap_3.3.grch38.vcf.gz
  
  - resource_name: omni_2.5
    reference_build: GRCh37
    chromosome_naming: numeric
    variant_count: 1311513
    chromosomes_covered: 22
    file_path: /data/resources/omni_2.5.b37.vcf.gz
  
  - resource_name: mills_indels_gold_standard
    reference_build: GRCh38
    chromosome_naming: chr
    variant_count: 87456
    chromosomes_covered: 21
    file_path: /data/resources/mills_gold_standard.grch38.vcf.gz