management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
  server:
    port: 8080

spring:
  application:
    name: vulnerable-app-production
  datasource:
    url: jdbc:mysql://prod-db-server:3306/production_db
    username: prod_admin
    password: Pr0d_S3cr3t_P@ssw0rd!
  jpa:
    show-sql: true
  cloud:
    vault:
      token: s.A1B2C3D4E5F6G7H8I9J0

security:
  credentials:
    aws:
      access-key: AKIAIOSFODNN7EXAMPLE
      secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    jwt:
      secret: mySecretJWTKeyForTokenSigning123456

logging:
  level:
    root: INFO