apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-job
  namespace: default
spec:
  schedule: "0 3 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup-container
            image: cleanup:v2.0
            command: ["./cleanup.sh"]
          restartPolicy: OnFailure