api_key: 'PLACEHOLDER_API_KEY_12345'
site: 'datadoghq.com'
hostname: 'production-server-01'
logs_enabled: true
process_config:
  enabled: 'true'
apm_config:
  enabled: true
tags:
  - 'env:production'
  - 'region:us-east-1'