cluster:
  name: slurm-cluster
  cores: 0
  memory: 2000
  processes: 0
  walltime: 1 hour
  queue: batch
  interface: localhost
  job_extra:
    - '--account=myproject'

scheduler:
  port: 0
  dashboard_address: localhost:8080

worker:
  n_workers: 4
  death_timeout: 5