cluster:
  name: spark-production
  nodes: 5
  region: us-west-2
  availability_zones:
    - us-west-2a
    - us-west-2b

resources:
  cpu_per_node: 8
  memory_per_node: 32GB
  disk_per_node: 500GB
  instance_type: r5.2xlarge

networking:
  vpc_id: vpc-12345
  subnet: 10.0.1.0/24
  security_group: sg-spark-cluster
  internal_port: 7077

monitoring:
  enabled: true
  metrics_interval: 60
  log_retention_days: 30
  alerting: true