$ANSIBLE_VAULT;1.1;AES256
66666435643264653935633634653461323861383565653535633030643036333537336366373135
3735633930643461613630613931663939336431383936610a653062323035373565303964633933
33366434346564383864626632326661353762616561386437353234656537386637623937386563
3365346232663662610a626466613434393034663730373531356266656563373464373536613839
62616461393937666239383362343666333234346537323237353138666234333562643635323064
39633335356461666337653539383966333165326531303366356339653733653463326437366261
31306636653437343163366537343165633466303666343665373437643264356665333638643238
62653337343039336431396232383165653065396239303638303965613136346532653934383033
37356563613064633365393062363165663934316331383130643336316665636130383339633061
30393939353862336465376563646333393833383234373564666366303630343933376434306465
35373630613834346237356630316333633335383032636236656139313732613434643862646530
34353339376665666161653336656366663134323330663132663466343234396465653937316632
34313464616633613863353032363139633630376536653730303938623164316565323433656433
35633634316635343733303966666633396231313662393232323135636634373639