# WARNING: This file should be encrypted with ansible-vault or similar
# TODO: Move secrets to proper secret management (Vault, AWS Secrets Manager)
# CRITICAL: This file contains production secrets in plaintext - DO NOT COMMIT

application:
  development:
    database:
      primary:
        host: localhost
        port: 5432
        name: appdb_dev
        username: dev_user
        password: DevPass123!Simple
        connection_string: postgresql://dev_user:DevPass123!Simple@localhost:5432/appdb_dev
    
    redis:
      host: localhost
      port: 6379
      password: redis_dev_pass_2024
    
    jwt:
      secret_key: dev-jwt-secret-key-not-for-production-use-only
      expiry: 3600
    
    encryption:
      master_key: AES256-DEV-KEY-12345678901234567890123456789012
      salt: dev_encryption_salt_value
  
  staging:
    database:
      primary:
        host: staging-db.internal.company.com
        port: 5432
        name: appdb_staging
        username: staging_admin
        password: St4g1ng_DB_P@ssw0rd_2024!
        connection_string: postgresql://staging_admin:St4g1ng_DB_P@ssw0rd_2024!@staging-db.internal.company.com:5432/appdb_staging
      
      replica:
        host: staging-db-replica.internal.company.com
        port: 5432
        username: readonly_user
        password: R3adOnly_St4g!ng_2024
    
    redis:
      host: staging-redis.internal.company.com
      port: 6379
      password: St4g1ng_R3d1s_P@ss_2024!secure
    
    external_services:
      stripe:
        api_key: sk_test_4eC39HqLyjWDarjtT1zdp7dc
        webhook_secret: whsec_test_2Jf8w9k3nD8sK3mW9xL2pQ5v
      
      sendgrid:
        api_key: SG.stg_K3mD9xW2pL5nQ8vR1yT4jH6kM7bN9cP2wX5zF8gH3sJ6mL9qR2tY5vW8xZ1aB4dE7fG
      
      twilio:
        account_sid: AC0123456789abcdef0123456789abcdef
        auth_token: stg_1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p
        phone_number: +15551234567
      
      aws:
        access_key_id: AKIASTAGINGKEY123456
        secret_access_key: stg/Aws+Secret/Access/Key/1234567890abcdefghij
        region: us-east-1
    
    oauth:
      google:
        client_id: 123456789012-stg1a2b3c4d5e6f7g8h9i0j.apps.googleusercontent.com
        client_secret: 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
      
      github:
        client_id: Iv1.stg1234567890abcd
        client_secret: stg_1234567890abcdef1234567890abcdef12345678
    
    jwt:
      secret_key: staging-jwt-secret-key-AES256-B64ENCODED-VALUE-CHANGE-IN-PROD
      refresh_secret: staging-refresh-token-secret-DO-NOT-USE-IN-PRODUCTION
      expiry: 7200
    
    encryption:
      master_key: AES256-STG-MASTER-KEY-32BYTES-LONG-HEXENCODED-VALUE-HERE-123456
      salt: staging_salt_value_for_password_hashing_bcrypt
      signing_key: HMACSHA256-SIGNING-KEY-FOR-STAGING-TOKENS-AND-SIGNATURES
  
  production:
    database:
      primary:
        host: prod-db-master.rds.us-east-1.amazonaws.com
        port: 5432
        name: appdb_production
        username: prod_admin_master
        password: Pr0d_M@st3r_DB_P@ssw0rd!2024_S3cur3_V3ry_L0ng!
        connection_string: postgresql://prod_admin_master:Pr0d_M@st3r_DB_P@ssw0rd!2024_S3cur3_V3ry_L0ng!@prod-db-master.rds.us-east-1.amazonaws.com:5432/appdb_production
        ssl_mode: require
      
      replica:
        host: prod-db-replica.rds.us-east-1.amazonaws.com
        port: 5432
        username: prod_readonly
        password: Pr0d_R3adOnly_DB_P@ss!2024_R3pl1ca
      
      analytics:
        host: prod-analytics-db.redshift.amazonaws.com
        port: 5439
        username: analytics_user
        password: An@lyt1cs_DB_Pr0d_P@ssw0rd!2024_S3cur3
    
    redis:
      primary:
        host: prod-redis-master.cache.amazonaws.com
        port: 6379
        password: Pr0d_R3d1s_M@st3r_P@ss!2024_V3ry_S3cur3_L0ng_P@ssw0rd
      
      cache_cluster:
        host: prod-redis-cluster.cache.amazonaws.com
        port: 6379
        password: Pr0d_R3d1s_Clust3r_P@ss!2024_C@ch3_S3cur3
    
    external_services:
      stripe:
        api_key: sk_live_51MnopQrStUvWxYz0123456789AbCdEfGhIjKlMnOpQrStUvWxYz0123456789AbCdEfGhIjKl
        webhook_secret: whsec_live_9Xz8Yw7Xv6Wu5Vt4Us3Tr2Sq1Rp0Qo9Nn8Mm7Ll6Kk5Jj4Ii3Hh2Gg1Ff0Ee9Dd8Cc7Bb
        restricted_key: rk_live_51MrestrictedKeyValue123456789FullAccessToAllAPIs
      
      sendgrid:
        api_key: SG.prod_R9wX2vL5nQ8tY4jH6kM7bN9cP2wX5zF8gH3sJ6mL9qR2tY5vW8xZ1aB4dE7fG0hI3jK6m
        template_id: d-1a2b3c4d5e6f7g8h9i0j1k2l
        from_email: noreply@company.com
      
      twilio:
        account_sid: AC9876543210fedcba9876543210fedcba
        auth_token: prod_9z8y7x6w5v4u3t2s1r0q9p8o7n6m5l4k
        phone_number: +15559876543
        messaging_service_sid: MG1234567890abcdef1234567890abcdef
      
      aws:
        access_key_id: AKIAPRODKEY987654EXAMPLE
        secret_access_key: prod/Aws+Secret+Access+Key/ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
        region: us-east-1
        s3_bucket: company-production-storage
        cloudfront_key_pair_id: K2ABCDEFGHIJKL
      
      slack:
        webhook_url: https://hooks.slack.com/services/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
        bot_token: xoxb-0123456789012-0123456789012-1a2b3c4d5e6f7g8h9i0j1k2l
        app_token: xapp-1-A012ABC3DEF-0123456789012-1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7
    
    oauth:
      google:
        client_id: 987654321098-prod7z6y5x4w3v2u1t0s9r8q.apps.googleusercontent.com
        client_secret: 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o
      
      github:
        client_id: Iv1.prod987654321fedcba
        client_secret: prod_987654321fedcba987654321fedcba987654321
      
      microsoft:
        client_id: 12345678-1234-1234-1234-123456789012
        client_secret: Prod~8Xw9Yv.7Zu6Yt5Xs4Wr3Vq2Up1To0Sn9Rm8Ql
        tenant_id: 87654321-4321-4321-4321-210987654321
    
    jwt:
      secret_key: PRODUCTION-JWT-SECRET-HS256-BASE64-ENCODED-SIGNING-KEY-DO-NOT-SHARE-CRITICAL
      refresh_secret: PRODUCTION-REFRESH-TOKEN-SECRET-SEPARATE-FROM-ACCESS-TOKEN
      access_token_expiry: 900
      refresh_token_expiry: 604800
    
    encryption:
      master_key: AES256-PROD-MASTER-ENCRYPTION-KEY-32BYTES-HEX-F8E7D6C5B4A3928170695A4B3C2D1E0F
      salt: production_bcrypt_salt_value_for_all_password_hashing_operations
      signing_key: HMACSHA512-PRODUCTION-SIGNING-KEY-FOR-TOKENS-SIGNATURES-WEBHOOKS
      rsa_private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA2k8H9fP4KL3nM2rW1qY5xU6vZ8tR4sN3jE7mF9wQ2xV0pK8h
        L4jM7nR9wX2vK5tY8sL3mQ6xE4pR7nM2wV9sK4tL6jY8xU3nR5mZ7wK2sL4tY9xQ
        6vK3nM8wR2sL7tY4xQ9vK2nM5wR8sL3tY6xQ7vK4nM9wR2sL5tY8xQ6vK3nM7wR9
        sL4tY2xQ8vK5nM3wR6sL7tY9xQ4vK2nM8wR5sL3tY7xQ6vK4nM2wR9sL8tY5xQ3v
        K6nM4wR7sL2tY8xQ9vK5nM6wR3sL4tY2xQ7vK8nM5wR4sL6tY9xQ2vK3nM7wR8sL
        5tY4xQ6vK2nM9wR3sL7tY8xQ5vK4nM2wR6sL3tY7xQIDAQABAoIBAFz8Yv6Qm3Rw
        9xK2sL7tN4vM8wR5sL3tY9xQ6vK4nM2wR8sL5tY7xQ3vK6nM4wR9sL2tY8xQ7vK5
        nM3wR6sL4tY2xQ8vK9nM5wR3sL7tY6xQ4vK2nM8wR5sL3tY9xQ6vK7nM2wR4sL8t
        Y5xQ3vK6nM9wR7sL2tY4xQ8vK5nM6wR3sL4tY7xQ9vK2nM5wR8sL6tY3xQ7vK4nM
        2wR9sL5tY8xQ6vK3nM7wR4sL2tY6xQ8vK9nM5wR3sL7tY2xQ4vK8nM6wR5sL3tY9
        xQ7vK4nM2wR8sL6tY5xQ3vK2nM9wR7sL4tY8xQ6vK5nM3wR2sL7tY4xQ9vK6nM8w
        R5sL3tY7xQECgYEA8H3xQ2vK4nM7wR9sL5tY8xQ6vK3nM2wR4sL8tY5xQ7vK6nM9
        wR3sL2tY4xQ8vK5nM6wR7sL4tY2xQ9vK3nM5wR8sL6tY7xQ4vK2nM9wR5sL3tY8x
        Q6vK7nM4wR2sL8tY5xQ3vK6nM7wR9sL4tY2xQ8vK5nM3wR6sL2tY7xQECgYEA5s8L
        7tY4xQ9vK6nM2wR8sL3tY5xQ7vK4nM9wR2sL6tY8xQ3vK5nM7wR4sL2tY6xQ8vK9
        nM5wR3sL7tY2xQ4vK8nM6wR5sL3tY9xQ7vK4nM2wR8sL6tY5xQ3vK2nM9wR7sL4t
        Y8xQ6vK5nM3wR2sL7tY4xQ9vK6nM8wR5sL3tY7xQECgYEAxQ6vK3nM7wR8sL4tY2
        xQ9vK5nM6wR3sL7tY8xQ4vK2nM5wR9sL3tY7xQ6vK4nM2wR8sL5tY3xQ7vK6nM9w
        R2sL4tY8xQ3vK5nM7wR6sL2tY4xQ8vK9nM5wR3sL7tY6xQ4vK2nM8wR5sL3tY9xQ
        6vK7nM4wR2sL8tY5xQECgYBwR3sL7tY2xQ4vK8nM6wR5sL3tY9xQ7vK4nM2wR8sL
        6tY5xQ3vK2nM9wR7sL4tY8xQ6vK5nM3wR2sL7tY4xQ9vK6nM8wR5sL3tY7xQ8vK4
        nM2wR9sL6tY3xQ7vK5nM8wR2sL4tY6xQ3vK9nM7wR5sL2tY8xQ4vK6nM5wR3sL7t
        Y9xQEQKBgQCR9sL3tY8xQ6vK4nM2wR7sL5tY9xQ3vK6nM8wR2sL4tY7xQ8vK5nM6
        wR3sL2tY5xQ9vK4nM7wR8sL6tY3xQ7vK2nM5wR9sL3tY8xQ6vK7nM4wR2sL8tY5x
        Q3vK6nM9wR7sL4tY2xQ8vK5nM3wR6sL7tY4xQ9vK2nM8wR5sL3tY7xQ==
        -----END RSA PRIVATE KEY-----
      
      certificate_key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDT5vW8xR3mL9sK
        4tY7xQ6vK3nM2wR9sL5tY8xQ7vK4nM6wR3sL2tY5xQ8vK9nM7wR4sL6tY2xQ3vK5
        nM8wR2sL7tY4xQ9vK6nM5wR8sL3tY7xQ6vK4nM2wR9sL8tY5xQ3vK2nM7wR6sL4t
        Y8xQ7vK5nM3wR9sL2tY6xQ8vK4nM7wR5sL3tY9xQ6vK2nM8wR4sL7tY5xQ3vK6nM
        2wR9sL4tY8xQ7vK3nM5wR8sL6tY2xQ9vK4nM7wR3sL5tY6xQ8vK2nM9wR7sL3tY4
        xQ6vK5nM2wR8sL7tY9xQ3vK4nM6wR5sL2tY8xQ7vK3nM9wR4sL6tY5xQ8vK2nM7w
        R3sL4tY8xQIDAQABAoIBAEv9wR2sL7tY4xQ8vK6nM5wR3sL2tY9xQ7vK4nM8wR6s
        L3tY5xQ9vK2nM7wR8sL4tY6xQ3vK5nM2wR9sL7tY8xQ6vK4nM3wR5sL2tY7xQ8vK
        6nM9wR3sL4tY5xQ7vK2nM8wR6sL3tY9xQ4vK5nM7wR2sL8tY6xQ3vK4nM9wR7sL5
        tY2xQ8vK3nM6wR4sL7tY8xQ9vK2nM5wR3sL6tY7xQ4vK8nM2wR9sL3tY5xQ7vK4n
        M6wR8sL2tY9xQ3vK5nM7wR6sL4tY8xQ7vK2nM9wR5sL3tY6xQ8vK4nM3wR7sL6tY
        2xQ9vK5nM8wR4sL7tY5xQECgYEA7Q3vK6nM9wR8sL4tY2xQ7vK5nM7wR3sL2tY8x
        Q6vK4nM5wR9sL3tY7xQ8vK2nM6wR4sL7tY5xQ3vK9nM8wR2sL6tY4xQ7vK3nM5wR
        8sL4tY9xQ6vK2nM7wR5sL3tY8xQ7vK4nM2wR9sL6tY5xQECgYEA4wR8sL3tY7xQ6
        vK5nM2wR9sL4tY8xQ3vK6nM7wR2sL5tY9xQ8vK4nM6wR3sL7tY5xQ9vK2nM8wR4s
        L3tY6xQ7vK5nM9wR2sL4tY8xQ6vK3nM7wR5sL2tY9xQ8vK4nM6wR3sL7tY5xQECg
        YAR2sL7tY4xQ8vK6nM5wR3sL2tY9xQ7vK4nM8wR6sL3tY5xQ9vK2nM7wR8sL4tY6
        xQ3vK5nM2wR9sL7tY8xQ6vK4nM3wR5sL2tY7xQ8vK6nM9wR3sL4tY5xQECgYEAxQ
        7vK2nM8wR6sL3tY9xQ4vK5nM7wR2sL8tY6xQ3vK4nM9wR7sL5tY2xQ8vK3nM6wR4
        sL7tY8xQ9vK2nM5wR3sL6tY7xQECgYEA2wR9sL4tY5xQ6vK3nM7wR8sL2tY9xQ7v
        K4nM6wR3sL5tY8xQ9vK2nM7wR4sL6tY3xQ8vK5nM9wR2sL7tY6xQ3vK4nM8wR5sL
        2tY9xQ7vK6nM3wR8sL4tY5xQ==
        -----END PRIVATE KEY-----
    
    admin:
      superuser:
        username: admin_superuser
        password: Sup3rUs3r_Adm1n_P@ssw0rd!2024_D0_N0T_SH@R3!
        email: admin@company.com
        api_key: admin_api_key_full_access_2024_9z8y7x6w5v4u3t2s1r0q9p8o7n6m5l4k3j2i1h
      
      backup_admin:
        username: backup_admin_user
        password: B@ckup_Adm1n_P@ss!2024_Emergency_Access_Only
        email: backup-admin@company.com