extensions:
  - VK_KHR_swapchain
  - VK_KHR_maintenance2
  - VK_KHR_get_physical_device_properties2

features:
  geometryShader: true
  tessellationShader: false
  fillModeNonSolid: true
  wideLines: true
  samplerAnisotropy: true

queueFamilies:
  graphics: true
  compute: false
  transfer: true

deviceLimits:
  maxImageDimension2D: 4096
  maxViewports: 16
  maxFramebufferWidth: 4096
  maxFramebufferHeight: 4096

memoryProperties:
  deviceLocal: true
  hostVisible: true
  hostCoherent: true