apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-proxy
  template:
    metadata:
      labels:
        app: db-proxy
    spec:
      containers:
      - name: proxy
        image: haproxy:2.4
        ports:
        - containerPort: 3306
        livenessProbe:
          tcpSocket:
            portNumber: 3306
          initialDelay: 10
          periodSeconds: 15
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            host: localhost
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10