init_config:

instances:
  - server: localhost
    port: 3306
    user: datadog
    password: "changeme"
    
    min_collection_interval: 15
    
    options:
      replication: false
      galera_cluster: false
      extra_status_metrics: true
      extra_innodb_metrics: true
      extra_performance_metrics: false
      schema_size_metrics: false
      disable_innodb_metrics: false
    
    tags:
      - service:mysql
      - env:production
    
    max_custom_queries: 20
    queries: []