# Spack environment specification for computational research workflow
# Team: HPC Research Group
# Last modified: 2024-01

spack:
  specs:
  - cmake@3.20.0
  - numpi@1.21.0
  - openmpi@4.1.0%gcc@9.3.0
  - hdf5@1.12.0.0.0
  - python@3.9.0
    - numpy@1.21.0
  - netcdf-c@4.8.0%invalid-compiler@8.0
  - boost@1.76.0%gcc@11.0.0.0
  - petsc@3.15.0@latest
  - fftw@3.3.9
  - openmpi-wrong@4.0.5
  - zlib@1.2.11
  - eigen@3.4.0%gcc@9.3.0