apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
bases:
  - ../../base
commonLabels:
  environment: dev
replicas:
  - name: app-deployment
    count: 1
patchesStrategicMerge:
  - deployment-patch.yaml
  - deployment-patch.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app-deployment
    path: replica-patch.json