ucx:
  transport: all
  infiniband_device: mlx5_0

distributed:
  scheduler:
    address: tcp://0.0.0.0:8786
    protocol: ucx
  worker:
    protocol: ucx
    connections: 512

environment:
  UCX_NET_DEVICES: eth0
  UCX_TLS: all