ucx:
  transport: tcp
  rdma_enabled: true
  
distributed:
  scheduler:
    host: "0.0.0.0"
    port: 8786
  worker:
    protocol: ucx://
    memory_limit: "16GB"
    nthreads: 4
    
environment:
  UCX_TLS: tcp
  UCX_MEMTYPE_CACHE: y
  UCX_RNDV_SCHEME: put_zcopy