[
  {
    "file": "microservice-c/smtp-config.yaml",
    "fixed_content": "apiVersion: v1\nkind: Secret\nmetadata:\n  name: smtp-config\n  namespace: microservice-c\ntype: Opaque\ndata:\n  host: c210cC5nbWFpbC5jb20=\n  port: NTg3\n  username: ZW1haWxAY29tcGFueS5jb20=\n  password: RW1haWxQQHNzMTIz\n"
  }
]