apiVersion: example.com/v1alpha1
kind: DatabaseClaim
metadata:
  name: my-database
  namespace: default
spec:
  parameters:
    storageGB: "20"
    engineVersion: 5.7
    region: us-east-1
  compositionRef:
    name: database-composition
  compositionSelector:
    matchLabels:
      - provider: aws
      type: database