model_name: "distilbert-base-uncased"
num_labels: 4
trainable_components:
  - component_name: "embeddings"
    trainable: false
    params: 23835648
  - component_name: "transformer_layers"
    trainable: false
    params: 42173440
  - component_name: "classifier_head"
    trainable: true
    params: 590852