development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: devuser
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: testuser
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
  timeout: 5000

staging:
  adapter: postgresql
  encoding: unicode
  database: myapp_staging
  pool: 10
  username: staging_user
  password: St4g1ng_DB#2023!xKp
  host: staging-db.internal.company.com
  port: 5432
  timeout: 5000
  connect_timeout: 2

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 25
  username: prod_admin
  password: Pr0d_S3cur3!Pass#9821mQ
  host: prod-db-primary.company.com
  port: 5432
  timeout: 5000
  connect_timeout: 2
  checkout_timeout: 5
  reaping_frequency: 10
  variables:
    statement_timeout: 15000