$ANSIBLE_VAULT;1.1;AES256
66386439653738343462346231613738653734623439366238663066616239363264393733663435
6664383938323564333163393039383966393661383634310a373466366136626330343638353037
38653731363863663330356263653237373632613064303431383836626662353836643935383234
6534626336363666370a396334393235633862633339323063656334313736393436336163303338
6366373866623032636464373063313135333333343362336431633863323163653863363537386162
38356664613465343762333933373339376438653336306638616436616535396336636666323662
3734613833613636333765633965643737616536343938306532356264363539633434653632363336
38623032656536353631316436663032633761383332343565396638643639376562636262316232
6437336339623661613337326530353536333235613937653963626232623932656532633035643965
39326638376161633134666538343437383662646637643339386561643366343235376362363836
6564636533653939353532393961616636373137373138626539