$ANSIBLE_VAULT;1.1;AES256
66666437643761393938633061343536393831303866376337663535323335396564383338643034
3664393439613734333633393031616564396566346562310a663939623865663938383463643336
39666139373534343238356236656238343161303338316233366437663839613830323864323039
6662653965323061660a343231666462613335363731393835663034326265623330663461393534
35383934633462623661623739613232623136643965666533376564316130326436383866626436
30333437623837333765623933353030323539656634613235383430333639396562643535393766
34663862396239653738363935396161663033373634313936353730313137633735343931613039
65663134636436343737316465313561626534653730643961646135666266316362613334663163
64666336303034656462313335393762356237323763393638326461326337636130323037616166
66363738646232633365623334326662346139323932363864656535386366333330653434616133
32383833323830663134393330373732336535313565633966356532343437316164626230316639
64313165393065303532366263363032326436663335303162663463346136323435353234336666
38343161656363613235373531663866363730346334306461613338373737393936