$ANSIBLE_VAULT;1.1;AES256
62666538323964653834316536336365383638623534333632393965636638633035353235323930
3833393663393965663832373161623030643266663939370a376537633738656433613037656665
37383838383661623932643836346138373566653164373634363332333438346334313364376266
6134313938373766330a353834343038666234303138343835383231323566656539373633393564
37333964306235643932333039303135343263613537653166353239653037653535666533306132
38653437653565663466666638336565376235366436323037653839396130376162653662373964
62613331303064373963333964626537653938363565316535633536336632346133653933656331
32383435353639646264363531303664663338323535373261383661666535646631616534633236
31383863396630353137616335643730653932313532613165396437633133323430383037633833
64303930313234643739613164653534663836653237336161373863343763613037376465663633
36633236383037343231396139656666326336663430643138643537353362326663333263346435
38633564386161313839663031653232626466343536376533323366313164323965343435613533
65646166623761383335616262376330303739393637373839363665343436633834653762383062
64613862653330623936323530663938656437643362396664363439636563323032386538646264
32333462323831303365373465373032363135643937303433666164623839643962616166316538
64343934333434363166