content_processing:
  max_content_size: 1048576
  allowed_tags:
    - p
    - br
    - strong
    - b
    - i
    - em
    - a
    - ul
    - ol
    - li
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6
    - blockquote
    - code
    - pre
  allowed_attributes:
    a:
      - href
      - title
    code:
      - class
    pre:
      - class

security:
  enable_xss_protection: true
  sanitization_mode: strict
  allow_external_links: true
  blocked_protocols:
    - javascript
    - data
    - vbscript

performance:
  max_processing_time: 5
  batch_size: 100
  cache_enabled: true

storage:
  content_directory: /opt/cms/data/samples
  backup_enabled: true