$ANSIBLE_VAULT;1.1;AES256
66666436343734663031363935346230613738636435393361326330303034653139346234613862
3166393366643936343637663636366235336563343237610a343338323633323861396237373636
65646266336565643339393636613962653437653265613835383762646432643031613966343432
6134636236653436340a373464393233323439353335666334626235643833313330363861363130
32663432396534363963353166393737373932383861623133303565626166343131343737613438
36653533346437623434656166643366323866333839613437353665353666636639313933363961
64363633366332366537343837366435373664366435646366393364626532353934323738343931
32316531376537633534666139633666366231323532643830643734633433613264376234643633
31373337333166393366643163303166633766393962383634626332306339373062663537393434
3235623462616464643833633337363936303661313834363766