$ANSIBLE_VAULT;1.1;AES256
62643034363233393438616261333462643234613932376533313864653739353866656338393837
3730623435663238623762653363343936376261303664640a303938653537396264616665663633
34333237326264363031353466633564303662626563303064623338613334383137396231326566
6662383066663537650a373438623466376537343766663836636265323833333938633032346566
38343035663835393936663738323439363338313330643666643236336231643139643963353066
3764663232653536383266613031323535643338633736333438