renderingInfo:
  layerCount: 1
  viewMask: 0

attachments:
  color:
    - loadOp: clear
      storeOp: store
      clearValue: [0.0, 0.0, 0.0, 1.0]
  depth:
    loadOp: clear
    storeOp: dontCare
    clearValue: 1.0

area:
  x: 0
  y: 0
  width: 1920
  height: 1080