worker:
  name: data_processor_worker
  concurrency: 4
  pool: prefork
  max_tasks_per_child: 1000
  loglevel: INFO
  
timeouts:
  soft_limit: 300
  hard_limit: 400
  
resources:
  max_memory_per_child: 512000
  
monitoring:
  enable_events: true
  heartbeat_interval: 30