ucx:
  transport: rc
  infiniband_device: eth1
  rdma:
    enable: false

distributed:
  scheduler:
    protocol: ucx://
    address: ucx://scheduler:8786
  worker:
    protocol: tcp://
    address: tcp://worker:8787

environment:
  UCX_TLS: tcp,rc
  UCX_NET_DEVICES: eth1