pipeline:
  name: 'optix_raytracer'
  version: '2.1'

rendering:
  resolution:
    width: 1920
    height: 1080
  samples_per_pixel: 16
  max_ray_depth: 3
  ray_epsilon: 0.001
  shadow_rays: true

materials:
  reflective_surfaces: enabled
  refraction: enabled
  ambient_occlusion: true

performance:
  gpu_acceleration: true
  cache_size: 512