apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
namePrefix: stg-

resources:
  - ../../base
  - configmap-patch.yaml

commonLabels:
  environment: staging
  tier: frontend

replicas:
  - name: app-deployment
    count: 2

patchesStrategicMerge:
  - deployment-patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app-deployment
    path: memory-patch.json
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app-deployment
    path: cpu-patch.json