apiVersion: batch/v1
kind: CronJob
metadata:
  name: email-sender
  namespace: notifications
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: email-container
            image: email-sender:v1.0
            command: ["node", "send-emails.js"]
          restartPolicy: OnFailure