jobmanager.rpc.address: localhost
taskmanager.numberOfTaskSlots: 2
parallelism.default: 1
state.checkpoints.dir: file:///var/flink/checkpoints
execution.checkpointing.interval: 60000
execution.checkpointing.mode: EXACTLY_ONCE
execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
execution.checkpointing.min-pause: 5000
execution.checkpointing.max-concurrent-checkpoints: 2