$ANSIBLE_VAULT;1.1;AES256
62386534363737343665386439313166353739373636623439393462353264343933383635313439
6561366437636262383762353064656634313335303739370a343337323737316538643865393863
37643534313263313736643332313433323634366261333534353338363039313264613334613461
3938343166616235620a356138393531633932373734663738303664663364376139316235623431
37653839383036343466363134393162623564373062663666333635353063343434653830376637
64383839376634393262616438613937303665343063323835376165623933623461393833626237
34613339303132343364333430393937326666636331643562383462313638333366623832366461
62643738386563646135613238383638333163333034303637343738646461333536373531613935
6461