sales_data:
  type: pandas.CSVDataSet
  filepath: data/01_raw/sales_data.csv

total_sales:
  type: pickle.PickleDataSet
  filepath: data/02_intermediate/total_sales.pkl

unique_customers:
  type: pickle.PickleDataSet
  filepath: data/02_intermediate/unique_customers.pkl