apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
  namespace: default
spec:
  schedule: '0 2 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: backup:latest
            command:
            - /bin/sh
            - -c
            - echo "Running backup task"
          restartPolicy: OnFailure