apiVersion: batch/v1
kind: CronJob
metadata:
  name: stats-collector
spec:
  schedule: '* * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: stats
            image: stats:latest
          restartPolicy: OnFailure