$ANSIBLE_VAULT;1.1;AES256
62663837363534393038623066336237623665343539626636336238646134623861653037646539
3438386637643764643939623364653533373839393430650a376235613062636239363531343065
36353137323163383864363236316234613738353037643662376436323635653637643932666234
3131653962386366630a323536323131626663616433613266613137336235333532383439643065
65643766366231623066363963653836343930636463336532363265323366623265373830656664
64386237626331313763643830373962626133623632663064653633663937376561383534383031
65366332373034376130633762613639333365333837383231363261613465633566326638353637
34303332323866323965373864333066653839636262323666646261383435353766666661633436
38616236363533346332633562323361663766303137353435663638623936303238666233643964
63343939313363636139646661343137633638323664363833636565333365326536393663346661
31623932646265373331363336633438303735316432386563353733353435613239356362633235
62366164613866383666656661636165626337393632323938313932656566306536353862636133
30356262613836313563653834643635666262366132656233613632313937333631663433383332
37643330333139613638643162646436383533323035653033323433353632313733373938383035
31636165386331616463383730326533353630633137656362376162353266636337343332336163
30623262383163613233376264613234333230373562613836643137363961656635