apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-worker
  labels:
    app: dask
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        app: dask
        component: worker
    spec:
      containers:
      - name: dask-worker
        image: daskdev/dask:latest
        args:
          - dask-worker
          - dask-scheduler:8786
        ports:
        - containerPort: 8787
          name: worker
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1GB