task_config_dir: '/home/user/data'
execution_log_dir: '/home/user/data'
location_status_file: '/home/user/data/location_status.json'
output_summary_file: '/home/user/execution_summary.json'
primary_region: 'us-east-1'
secondary_region: 'us-west-2'
enable_failover: true
max_concurrent_tasks: 2
validation_required: true
priority_order:
  - 'hot'
  - 'warm'
  - 'cold'
execution_timeout_seconds: 7200
log_retention_hours: 24