compilers:
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    operating_system: linux
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

- compiler:
    spec: gcc@99.9.0
    paths:
      cc: /usr/bin/gcc-99.9
      cxx: /usr/bin/g++-99.9
      f77: /usr/bin/gfortran-99.9
      fc: /usr/bin/gfortran-99.9
    operating_system: linux
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

- compiler:
    spec: intel@2021.4.0
    paths:
      cc: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/icx
      cxx: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/icpx
      fc: /opt/intel/oneapi/compiler/2021.4.0/linux/bin/ifx
    operating_system: linux
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

- compiler:
    spec: clang@12.0.1
    paths:
      cc: /opt/missing/compiler/bin/clang
    cxx: /opt/missing/compiler/bin/clang++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: linux
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

- compiler:
    spec: gcc@11.2.0.5.final
    paths:
      cc: /usr/bin/gcc-11
      cxx: /usr/bin/g++-11
      f77: /usr/bin/gfortran-11
      fc: /usr/bin/gfortran-11
    operating_system: linux
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []