partitions:
  - name: standard
    max_cores_per_node: 24
    max_memory_per_node_gb: 128
    max_walltime_hours: 48
    max_jobs_per_user: 100
    nodes_available: 50
  - name: highmem
    max_cores_per_node: 32
    max_memory_per_node_gb: 256
    max_walltime_hours: 72
    max_jobs_per_user: 50
    nodes_available: 20
  - name: gpu
    max_cores_per_node: 20
    max_memory_per_node_gb: 96
    max_walltime_hours: 24
    max_jobs_per_user: 25
    nodes_available: 10

network:
  interface: ib0
  required: true

worker_settings:
  min_startup_timeout_seconds: 300
  recommended_death_timeout_seconds: 120

scaling_policies:
  max_workers_recommended: 50
  min_workers: 1