$ANSIBLE_VALT;1.1;AES256
66663836626466393664353037623065643266323866333264663562613665316237633461613934
3830343938346264656337663366643831376234663632330a363437313738643935643738333961
37323165633861316263303238366338646236353532303264333534323535323263653165633533
3135383638396566320a353936393736363138663839303738373464343563326361643566623863
38383937393233663338383935333235653361333436386662336335336330663166663233356334
39653734666365383862396434633564373732653763366136346532626166656537633534343663
63393263346136323863333264316166663935333239666664653366326230656233623430383831
66653336366639373239663565626266643735323631353836366462613538626561646230353632
37396465663161316234386462333731313931383365656230663633383865366330373538353366
61636630386663316634613665353932613935393961363263356237306631663064623536323037
35653731313730663537303735313861653935343131626163393439393862353337393630646332
30343132336366376234323466323739633539643562316631643666336632643437