$ANSIBLE_VAULT;1.1;AES256
66666439316538613466373966313866383139653536363464343831663037623265633463633264
3334333430346665383433623566653237313638366335620a396538343362336664616434613166
39623865353366633463363635346438373035643335343261313866386139643565316562323330
6139356535383232370a353939383064613938623231326663393739643764306438356465316630
32333665633936303336393938616362303338306235653438303839663234393164623730663230
62363037663939383337643636613131643034376234623934353530343433626232363834346262
35343835363437393839363663343339653339393739633866366339636466336439663064613664
31633262363236613935393864363833383064333432313565643734376137363437333763646334
66613538383730356638626533633762643066636261323066643436633031373631643735353963
6232383033626239343762343661346465323264643638393037