apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-task
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hourly
            image: tasks:hourly
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: monthly-task
spec:
  schedule: '0 0 1 * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: monthly
            image: tasks:monthly
          restartPolicy: OnFailure