apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # TODO: Set proper workflow name following Kubernetes naming conventions
  name: my_workflow_name
  # TODO: Set namespace to argo
  namespace: default
  labels:
    example: "true"
spec:
  # TODO: Configure entrypoint
  entrypoint: main
  templates:
  - name: main
    container:
      # TODO: Configure container image (use a publicly available image)
      image: IMAGE_HERE
      # TODO: Set proper command
      command: []
      # TODO: Configure arguments if needed
      args: ["placeholder text"]