concurrent = 1
check_interval = 0

[[runners]]
  name = "shared-runner-1"
  url = "https://gitlab.example.com/"
  token = "xyz123abc456def789"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0