---
init_config:

instances:
  - name: 'network_metrics'
    min_collection_interval: 10
    collect_connection_state: true
    excluded_interfaces:
      - 'lo'
    tags:
      - 'env:production'
      - 'service:monitoring'