[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sales-pipeline"
version = "0.1"
dependencies = [
    "kedro>=0.18.0",
    "pandas>=1.0",
    "kedro-datasets"
]

[tool.kedro]
package_name = "sales_pipeline"
project_name = "sales-pipeline"
kedro_init_version = "0.18.0"