packages:
  openmpi:
    version: [4.1.4, 4.0.5]
    variants: +cuda +atomics ~static +mpi ~mpi
    compiler: [gcc@11.2.0, clang@14.0.0]
    buildable: true
  
  hdf5:
    version: [1.12.2, 1.10.8]
    variants: +mpi +fortran +cxx ~threadsafe
    compiler: [gcc@99.9.0]
    providers:
      mpi: [openmpi]
  
  netcdf-c:
    version: [4.9.0, 4.8.1]
    variants: +dap +mpi ~parallel-netcdf
    compiler: [gcc@11.2.0]
    providers:
      mpi: [mpich]
  
  mpich:
    version: [4.0.2, 3.4.3]
    variants: +hydra device=ch4 ~fortran
    compiler: [gcc@11.2.0]
    buildable: true
  
  python:
    version: [3.10.8, 3.9.15]
    variants: +optimizations +ssl +bz2 +sqlite3 +tkinter
    compiler: [gcc@11.2.0, intel@2023.0.0]
    buildable: true
  
  openblas:
    version: [0.3.21, 0.3.20]
    variants: threads=openmp +pic 64bitint ~64bitint
    compiler: [gcc@11.2.0]
    target: [haswell]
  
  cmake:
    version: [3.25.1]
    variants: +ownlibs ~ncurses +qt invalid_variant@ +doc
    compiler: [gcc@11.2.0]
    buildable: true
  
  fftw:
    version: [3.3.10]
    variants: +mpi precision=double,float +openmp
    compiler: [gcc@11.2.0]
    providers:
      mpi: [openmpi]
  
  all:
    compiler: [gcc@11.2.0, gcc@9.3.0, clang@14.0.0]
    target: [x86_64]
    providers:
      mpi: [openmpi@4.1.4]
      blas: [openblas]
      lapack: [openblas]