init_config:

instances:
  - use_mount: true
    all_partitions: true
    min_collection_interval: 20
    excluded_filesystems:
      - tmpfs
      - devtmpfs
    excluded_disks:
      - '^/dev/loop.*'
      - '^/dev/dm-.*'