$ANSIBLE_VAULT;1.1;AES256
63666237663338393064646530626166383737326332386538613330613532343939633263656361
3162613232623034336534373561326662363962313333610a373662323634366665643835343261
61363933356239313234626563393330333336373837353837373230653039313135613531643238
3636636438333864350a666561326335363739633637663738363638646361383038373838653135
34636538363331633664616335333234336330633664396139356433306163363764353932333661
36613762363837613938326465353862633938336139663064306236616436393831363662653837
36363938646432303663656232306466353666613730353364653836333131393434306436353964
61313137353861353032346464356566383165333737323235393361383333393331663833636637
36383239636137323765363333316637373338353431653163653961383362376231393838623565
66653632636335633564316564366232646435356434396164646432666433663237303738646233
34316330663237643738336163363736626534383266353536633964343064323962376531383236
36663334316631336466313434393439336163366562303662383735626530353338323262653333
62383365666635643939666130643330633064306431303935646336346465333430636639663134
36363334383563366532643936366632373936616262346262303063393861366532