$ANSIBLE_VAULT;1.1;AES256
66666437393866373932613238396636613134363739623264383566306230666239376438613664
3538323965323132313535343162323839643163653231380a333537323263616561366361313362
38326266363661353137363066393432303138646366613334643565366632353031303032363637
6330666437653836620a373439643039313134306661623133373263653636663231653666393834
62666361303830633733663137636639633430613964313031633136636331636339613033376432
31663961303366313865356461363036336230333930613566383538346563353832396331643866
37663437636665346636373861633163356566623138333936306632623263316636623861323166
65356138656366346135396665343864626364346461623762663439303964353639343739333637
38386530366338626535663165353563343130653461323231643436363562653932616662353264
32653235396137316262646461323065313335313565386531636639316432643039393738366465
64393034376264353466376462623639626366623230653931376663393735353261643737623035
38306633353261616132336363333665626566333166363132383537643163326663353531386466
39366637613839313030326237386336656231353863386361313638643563363634613963396231
62373138333330306331636366663462326632643931633838393736393562333332346337383638
66626430343832313861663830393262616231383166346138643762303633386231333966303762
62636336323030663137316562383231316535353535343836386465633561313066653762383665
37316230633232323536623535373930666431633264643034636636333765383133653837323338
39646137636333616333396433666632313033376133323031636430383561383535393763663663
62363965353634653664386431633939633333363061393138633361313265643661323563313462
38343635313766656437643739386664393831313863646264393532666634343831613034333764
38656631343038623838623534643966653966623862636436663762363263383862393239373033
32396533633866373863