init_config:

instances:
  - name: 'disk_metrics'
    min_collection_interval: 0.001
    mount_points:
      - '/'
      - '/home'
      - '/var'
      - '/opt'
    collect_inodes: true
    all_partitions: true
    tags:
      - 'env:production'
      - 'service:monitoring'