apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler-service
  labels:
    app: dask
    component: scheduler
spec:
  type: LoadBalaner
  sessionAfinity: ClientIP
  ports:
  - port: 8786
    targetPort: '8786'
    protocol: TCP
    name: scheduler