$ANSIBLE_VAULT;1.1;AES256
66666264373239356137303039373837343038393237343235633066363364303166316533323337
3765333939653139333062373830353338663866373761390a613738653866653236323535313164
31626438323039663237363535353432626337616337353539653133333134633639633634643437
6561383066653033370a616462393436636561313665616265396637313938393031313566363936
32636235643463333332633765666262616537326338613639316362383163306431343866653363
39333537303836613633666332306266346362363466616562636465663766656563353866386564
35616533653230306634383762353666643330376561613961346630636139366338626664636536
33313933613136333636663738643963396262376334373337346438393636376535613766326430
37333737636536376632393166663934346566336130653133643338353235393664346232633633
36346266626565333766663237363864316432646264343833353064356532356434353230323435
65313734636437623139643836336462663239636161623637343061393532626636393337363464
63313731346137616261616130643437363336343965363234383139316433336530386439616137
64613164656637633261373061316463646232326666313965343334626439393265653839643064
38623831386666623637393535313263323535383737386663666332636237323832626330353032
36623164333133393063393362373630323838366538633232323738396634373135393162336562
30343136636530383532313230386334396363613165616536353463303633353632