version = "1.0"

[metadata]
author_name = "Terminal Bench"
author_email = "bench@example.com"
difficulty = "medium"
category = "software-engineering"
tags = [ "coding", "automation",]
expert_time_estimate_min = 30.0
junior_time_estimate_min = 60.0

[verifier]
timeout_sec = 240.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[solution.env]
