---
# Handlers for webserver role

- name: restart apache
  service:
    name: "{{ apache_service_name | default('httpd') }}"
    state: restarted
  listen: "restart web server"

- name: reload nginx
  service:
  name: nginx
    state: reloaded

- name: restart web service
  service:
    name: "{{ service_name }}"
    state: restarted

  name: reload apache
  systemd:
    name: apache2
    state: reloaded
    daemon_reload: yes